### ISSUE TITLE
-AutoFit Gives a warning

### ISSUE THREAD

**Issue by rlburkey** [EvotecIT/PSWriteExcel#10]
I have been using your PS Module today, and so far its fantastic!  When I try to use the -AutoFit flag on the Add-ExcelWorksheetData command or try to use Set-ExcelWorksheetAutoFit commande I get the following error:

WARNING: Set-ExcelWorksheetAutoFit - Failed AutoFit with error message: Exception calling "AutoFitColumns" with "0" argument(s): "The type initializer for 'Gdip' threw an exception."

Examples of both lines are:
Add-ExcelWorksheetData -ExcelWorksheet $ExcelWorksheet -DataTable $MyData -AutoFit -AutoFilter  -FreezeTopRow
Set-ExcelWorksheetAutofit -ExcelWorksheet $ExcelWorksheet 

Any Help is appreciated!  Thanks!

**Comment by PrzemyslawKlys** [comment]
https://evotec.xyz/powershell-core-the-type-initializer-for-gdip-threw-an-exception/
