### ISSUE TITLE
Get-Children -Recurse hangs when piped to ConvertTo-Excel

### ISSUE THREAD

**Issue by WearAHelmet** [EvotecIT/PSWriteExcel#4]
Get-ChildItem -Path ./Documents | ConvertTo-Excel -FilePath /home/vern/test/t.xlsx # Works fine

Get-ChildItem -Path ./Documents -Recurse | ConvertTo-Excel -FilePath /home/vern/test/t.xlsx # Hangs

Running on: Linux casey 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

PSWriteExcel 0.1.5

**Comment by PrzemyslawKlys** [comment]
Maybe there are a lot of files to process? How long have you waited?

**Comment by WearAHelmet** [comment]
Your question made me go back and test again. It turns out that it does finish, and I think I was underestimating how large of a file Get-ChildItem -Recurse might create. Guess it was a performance issue. Sorry.

**Comment by PrzemyslawKlys** [comment]
No problem :-)
