### ISSUE TITLE
Set-ExcelWorkSheetCellStyleFont  doesn't work to change the color of a cell

### ISSUE THREAD

**Issue by GiriSudh** [EvotecIT/PSWriteExcel#8]

**Comment by GiriSudh** [comment]
Following code gives error :
**Set-ExcelWorkSheetCellStyleFont  -ExcelWorksheet $ExcelWorkSheet -CellRow 2 -CellColumn 3 -Bold $True -Family 3 -Size 20 -Color Red**

Set-ExcelWorkSheetCellStyleFont : Cannot process argument transformation on parameter 'Color'. Cannot convert the "Red" value of type "System.String" to type "System.Nullable".
At line:24 char:129
+ ... Row 2 -CellColumn 3 -Bold $True -Family 3 -Size 20 -Color Red  
+                                                               ~~~
    + CategoryInfo          : InvalidData: (:) [Set-ExcelWorkSheetCellStyleFont], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-ExcelWorkSheetCellStyleFont

**Comment by PrzemyslawKlys** [comment]
I've rewritten the cmdlet.

This example works now. You need to update pswriteexcel to new version.

```powershell
$FilePath = "$Env:USERPROFILE\Desktop\PSWriteExcel-Example-SetExcelWorkSheetCell.xlsx"

$Excel = New-ExcelDocument -Verbose

$ExcelWorkSheet = Add-ExcelWorkSheet -ExcelDocument $Excel -WorksheetName 'Test 1' -Suppress $False -Option 'Replace'

$myitems0 = @(
    [pscustomobject]@{name = "Joe"; age = 32; info = "Cat lover" },
    [pscustomobject]@{name = "Sue"; age = 29; info = "Dog lover" },
    [pscustomobject]@{name = "Jason another one"; age = 42; info = "Food lover"
    }
)
Add-ExcelWorksheetData -ExcelWorksheet $ExcelWorkSheet -DataTable $myitems0 -AutoFit -AutoFilter -Suppress $True

Set-ExcelWorkSheetCellStyle -ExcelWorksheet $ExcelWorkSheet -CellRow 1 -CellColumn 2 -Name 'Arial' -Size 20 -Color Red -Bold -Italic -UnderLine -UnderLineType Double

Save-ExcelDocument -ExcelDocument $Excel -FilePath $FilePath -OpenWorkBook
```
